2022-06-19 19:33:44,773 ERROR rest_utils.py:build_response:61  Response: 500 Internal server error {'non_field_errors': ["'AnonymousUser' object has no attribute 'auth_token'"]} None
2022-06-19 19:33:44,775 DEBUG rest_utils.py:build_response:78  Response: 200 OK 500 Internal server error {'non_field_errors': ["'AnonymousUser' object has no attribute 'auth_token'"]} None
2022-06-19 19:34:13,813 DEBUG rest_utils.py:build_response:78  Response: 200 OK 200 User Successfully Login None None
2022-06-19 19:34:17,960 ERROR rest_utils.py:build_response:61  Response: 500 Internal server error {'non_field_errors': ["'AnonymousUser' object has no attribute 'auth_token'"]} None
2022-06-19 19:34:17,960 DEBUG rest_utils.py:build_response:78  Response: 200 OK 500 Internal server error {'non_field_errors': ["'AnonymousUser' object has no attribute 'auth_token'"]} None
2022-06-19 19:34:43,742 ERROR rest_utils.py:build_response:61  Response: 500 Internal server error {'non_field_errors': ["'User' object has no attribute 'auth_token'"]} None
2022-06-19 19:34:43,742 DEBUG rest_utils.py:build_response:78  Response: 200 OK 500 Internal server error {'non_field_errors': ["'User' object has no attribute 'auth_token'"]} None
2022-06-19 19:34:49,664 ERROR rest_utils.py:build_response:61  Response: 500 Internal server error {'non_field_errors': ["'User' object has no attribute 'auth_token'"]} None
2022-06-19 19:34:49,665 DEBUG rest_utils.py:build_response:78  Response: 200 OK 500 Internal server error {'non_field_errors': ["'User' object has no attribute 'auth_token'"]} None
2022-06-19 19:35:38,387 ERROR rest_utils.py:build_response:61  Response: 500 Internal server error {'non_field_errors': ["'User' object has no attribute 'auth_token'"]} None
2022-06-19 19:35:38,392 DEBUG rest_utils.py:build_response:78  Response: 200 OK 500 Internal server error {'non_field_errors': ["'User' object has no attribute 'auth_token'"]} None
2022-06-19 19:35:39,812 ERROR rest_utils.py:build_response:61  Response: 500 Internal server error {'non_field_errors': ["'User' object has no attribute 'auth_token'"]} None
2022-06-19 19:35:39,812 DEBUG rest_utils.py:build_response:78  Response: 200 OK 500 Internal server error {'non_field_errors': ["'User' object has no attribute 'auth_token'"]} None
2022-06-19 19:42:55,251 ERROR rest_utils.py:build_response:61  Response: 500 Internal server error {'non_field_errors': ["local variable 'e' referenced before assignment"]} None
2022-06-19 19:42:55,251 DEBUG rest_utils.py:build_response:78  Response: 200 OK 500 Internal server error {'non_field_errors': ["local variable 'e' referenced before assignment"]} None
2022-06-19 19:43:18,860 DEBUG rest_utils.py:build_response:78  Response: 200 OK 200 Logged Out None None
2022-06-19 19:43:21,486 DEBUG rest_utils.py:build_response:78  Response: 200 OK 200 Logged Out None None
